In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))
print(b[0,2],b[1,-1])


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
3 6


In [ ]:
# array slicing
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6]])
print(a[3:])

print(b[0,0:3])


[4 5]
[1 2 3]


In [ ]:
# array reshape
n=np.array([1,2,3,4,5,6])
print(n.shape)
print(n.reshape(2,3))

(6,)
[[1 2 3]
 [4 5 6]]
